### ISSUE TITLE
python-zope.interface needed

### ISSUE THREAD

**Issue by eravion** [Viblast/hls-proxy#7]
Hello,

Fyi, python-zope.interface package is mandatory for Twisted

BTW, once installed, it works fine.
Thanks :)

**Comment by svetlin-mladenov** [comment]
Thanks for pointing that out. I added it to the list of dependencies.

**Comment by svetlin-mladenov** [comment]
Thanks for pointing that out. I added `zope.interface` to the list of dependencies in README.md
